### DISCUSSION TITLE
Release v0.0.010: External auth provisional support

### DISCUSSION THREAD

**Discussion by DeanWard** [ErugoOSS/Erugo#32] [Announcements]
I'm excited to announce Erugo v0.0.010, featuring provisional external authentication provider support! This release allows administrators to configure multiple OAuth and OpenID Connect providers, giving your users more flexible login options while maintaining security.

### External Authentication System
- Added support for multiple authentication providers
- Built-in support for:
  - Google
  - Microsoft
  - Authentik
  - Generic OpenID Connect (OIDC)
- Configurable through the admin interface
- Secure OAuth2 implementation with proper callback handling

### Authentication Management
- Admin UI for managing authentication providers
- Ability to enable/disable providers individually
- Configuration validation to ensure proper setup
- Support for provider-specific parameters (tenant IDs, base URLs, etc.)
- Visual provider selection on login page with icons

### UI Enhancements
- Improved login screen with authentication provider options
- Enhanced settings interface for authentication configuration
- Better form validation and error handling

## 📋 Admin Instructions

To configure external authentication providers:
1. Navigate to Settings > System > Auth Providers
2. Click "+" button
3. Select a provider type and configure required fields - Erugo will display the callback URL for you to add to external provider
4. Enable the provider
5. Use the provided callback URL in your external provider configuration

<hr /><em>This discussion was created from the release <a href='https://github.com/DeanWard/erugo/releases/tag/v0.0.010'>Release v0.0.010: External auth provisional support</a>.</em>

**Comment by M4xS0ch** [comment]
Hi, it works like a charm!
Tested with Authelia (Caddy as reverse proxy) without any issue.
 From my understanding, only existing user can linked their account to a provider. Hence, no new user existing on provider can login.
Is there a plan to add an "auto-register" features? 
Max

**Reply by DeanWard** [reply]
Excellent! Thank you for letting me know you got this working :)

Yeah, right now only existing users can link their account. I've laid the groundwork for auto-register but its not ready just yet. I'll allow you to "trust" certain providers, then Erugo will allow account creation from them.

**Reply by massimilianorighi** [reply]
Hi there, 

I'm also a user of Authelia + Caddy with Erugo.
I'd like to highlight the step by step instructions for Authelia to works with Erugo.

1. In Erugo settings activate Open ID Connect as `Auth Provider` and copy the auto-generated callback URL.
2. Enable and allow self-registration options.
3. Add the following client to Authelia `configuration.yaml`: 
```
      - client_id: '<client-ID>'
        client_name: 'Erugo'
        client_secret: '<Digest-generated-ID>'  # The digest of 'insecure_secret'.
        public: false
        authorization_policy: 'two_factor'
        require_pkce: false
        pkce_challenge_method: ''
        redirect_uris:
          - '<Erugo-generated-callback>'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
          - 'groups'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
``` 
4. Restart Authelia
5. Try login
